# Site
name: "Visual Poetry Backup"
title: "Visual Poetry"
description: >-
  This is a backup of all visual poetry posted (with an image) into <a href="https://warpcast.com/~/channel/visual-poetry" target="_blank">Visual Poetry</a> channel.
tagline: Backup of visual poetry warpcast channel
logo: "assets/visual.png"
# favicon: 'assets/images/logo.png'
baseurl: ""
url: ""
permalink: :slug.html
include: ["_pages"]

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-figure

# Pagination

paginate: 12
paginate_path: /page:num/

# Other
highlighter: none
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true

feed:
  posts_limit: 25

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "enabled"

collections:
  authors:
    output: true
    permalink: /user/:title
    sort_by: displayname

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock, "warpcast.rb", "README.md", ".gitignore", "_json"]
